# Generated by Django 4.2.1 on 2023-06-04 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_account_is_checkout_alter_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_count', models.IntegerField()),
                ('card_number', models.CharField(max_length=16)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='website.starteduser')),
            ],
        ),
    ]
