# Generated by Django 4.2.1 on 2023-06-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=32)),
                ('api_hash', models.CharField(max_length=64)),
                ('max_account', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProxyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('max_account', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='cli_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cli_accounts', to='website.cliinfo'),
        ),
        migrations.AddField(
            model_name='account',
            name='proxy_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_accounts', to='website.proxyinfo'),
        ),
    ]
