# Generated by Django 4.2.1 on 2023-06-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_cliinfo_proxyinfo_account_cli_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cli_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cli_accounts', to='website.cliinfo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='account/profiles'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='website.starteduser'),
        ),
    ]
