# Generated by Django 4.2.1 on 2023-06-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_account_cli_info_alter_account_image_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='app_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='device_model',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='system_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliinfo',
            name='can_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proxyinfo',
            name='can_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliinfo',
            name='max_account',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proxyinfo',
            name='max_account',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(0, 'View'), (1, 'Join')])),
                ('count', models.IntegerField()),
                ('start_at', models.DateTimeField()),
                ('accept_to_start', models.BooleanField(default=False)),
                ('link', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Wating'), (1, 'Running'), (2, 'Finished')])),
                ('success_count', models.IntegerField(default=0)),
                ('faild_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.starteduser')),
            ],
        ),
    ]
