# Generated by Django 4.2.1 on 2023-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_account_app_version_account_device_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proxyinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
